<?php

return [
    'text-name-pasteiga' => 'Nelielajai pastaigai no mājām līdz dzelzceļa stacijai vajadzētu būt manas dienas mierīgajam sākumam. Rīta pastaiga pa skolas laikā tik ļoti iepazīto Rīgas ielu. Garām pirms 10 gadiem iestādītajam kokam, kas nu jau augstumā sāk līdzināties pārējiem apkārtnes kokiem. Galvā atceroties, kā pirmajās klasēs mani vecmamma pavadīja uz mājām no skolas pa šo pašu ielu. Mierīgās pastaigas laikā parādās sajūta, ka es varētu nokavēt vilcienu. Sākot nedaudz steigties, pastaiga kļūst par pasteigu.',
    'text-description-pasteiga-1' => 'Lai gan ceļā uz staciju man sanāk iet pa vairākām ielām, divas galvenās ielas ir Rīgas iela un Stacijas iela. Rīgas iela palīdz savienot blakus esošo Vidzemes šoseju ar pilsētas centru. Tas nozīmē, ka automašīna plūsma uz šīs ielas ir ļoti aktīva dienas laikā. Diemžēl man ir jāšķērso Rīgas iela, lai tiktu uz staciju. Es saku diemžēl, jo uz Rīgas ielas ir tikai viena gājēju pāreja ielas galā. Pārējos krustojumos gājējiem ir jāgaida līdz varēs paspēt tikt pāri ielai, nenonākot zem mašīnas riteņiem. Naktī, kad autobraucēji ir devušies gulēt, vienīgi ir mierīgāk. Baltajām ielas gaismām izgaismojot tukšo ceļu, rodas miera sajūta, kas liek aizmirst dienā sastapto saspringumu.',
    'text-description-pasteiga-2' => 'Dodoties tālāk pa Rīgas ielu varu redzēt gan jaunākas, gan vecākas mājas. Vairākas mājas ir uzceltas vai atjaunotas kopš es sāku dzīvot Siguldā. Dažas pakalpojumu ēkas ir pārvākušās uz citām telpām. Piemēram, vecās “SEB” bankas ēkas vietā tagad ir Siguldas Iespēju māja, kas vienuviet apvieno dažādas organizācijas, kas palīdz cilvēkiem ar īpašām vajadzībām. Pirms pāris gadiem uz Rīgas ielas tika uzzīmētas velojoslas uz brauktuves. Kaut arī tās izmanto velobraucēji, tās nav visai veiksmīgas, jo tās nav atdalītas no brauktuves ar kādiem fiziskiem elementiem. Papildus, tās parāda šīs ielas būtisku trūkumu – uz Rīgas ielas ietves ir tikai vienā ielas pusē, bet mājas ir abās ielas pusēs. Tāpēc gājēji dažreiz izmanto velojoslu kā ietvi.',
    'text-description-pasteiga-3' => 'Lielākoties es eju ar kājām uz staciju, jo tā ir aptuveni 10 min attālumā no manām mājām, bet es varu arī braukt ar riteni. Šādi ceļu varu veikt aptuveni 5 min. Ar riteni es braucu vairāk pavasarī un vasarā, kad ir saulains un patīkams laiks, jo pēc atbraukšanas atpakaļ uz Siguldu es varu doties nelielā izbraucienā ar riteni, dodoties mājās. Jāmin, ka man arī labprāt patīk doties pastaigās pa pilsētu. Rīgas ielas beigās es pagriežos uz Stacijas ielu un dodos tālāk paralēli dzelzceļa sliedēm. Es pāreju pāri dzelzceļam, un esmu sasniedzis staciju.',
    'text-name-gaidisana' => 'Pirmais galamērķis ir sasniegts, un es neesmu nokavējis vilcienu. Ja vilciens sāk ceļu no Siguldas, tad varu uzreiz doties meklēt vietu vilcienā. Citādi atliek vien sagaidīt, kad atbrauks vilciens vest mani un pārējos pasažierus tālāk uz Rīgas pusi. Stāvot uz perona, redzi, kā tas lēnām piepildās ar citiem braucējiem. Dažādi cilvēki sanākuši vienuviet, lai dotos vienā virzienā, bet ne uz vienu galamērķi. Kādus cilvēkus es varu atpazīt. Citus es redzu pirmo un varbūt pēdējo reizi. Lai arī mēs nepazīstam visi viens otru, mūs vieno šis gaidīšanas brīdis. Pienākot vilcienam, mēs izšķīstam un dodamies katrs savā dzīvē, piedzīvojuši īso un maznozīmīgo kopības sajūtu starp nepazīstamiem cilvēkiem.',
    'text-description-gaidisana-1' => 'Pirms pienāk vilciens man ir vēl nedaudz laika pastaigāt apkārt stacijai. Es varu izmantot iespēju apskatīt Stacijas laukumu un tā apkārtni. Kopš stacijas pārbūves, vienā vietā atrodas gan dzelzceļa stacija, gan autoosta, ir izveidots jauns Stacijas laukums ar savu “Laimas” pulksteni, kuru Sigulda ieguva pirms apmēram desmit gadiem. Staciju ieskauj divas dažādas zaļās zonas: vienā pusē ir neliels parks ar veco ūdenstorni, kas kādreiz ir kalpojis par mākslas izstāžu zāli, bet otrā pusē ir ar krūmiem aizaugusi teritorija, kas nepieder pašvaldībai. Jau gadus šīs zemes īpašnieks ir minējis, ka to apbūvēs, bet tas nav noticis. Pagaidām šo teritoriju var patīkami izmantot, lai tiktu līdz stacijai no gājēju pārejas, kas iet pāri sliedēm. No stacijas priekšpuses ir redzama Ausekļa iela ar tās vecajām ēkām, kafejnīcām un veikaliem, kā arī Latvijas pirmā veloiela – Pils iela.',
    'text-description-gaidisana-2' => 'Stāvot uz perona, var rasties bažas par to, vai esi nostājies uz pareizā ceļa. Pērkot biļeti lietotnē, tas netiek parādīts uz biļetes. Ieejot stacijā, ir redzams gaidāmā vilciena pienākšanas laiks, bet ne ceļa numuru. Jāpiemin nesens gadījums, kad klase, vēloties atgriezties atpakaļ Rīgā pēc došanos ekskursijā uz Siguldu, nostājās uz nepareizā ceļa. Pienākot vilcienam, viņi ātri pārskrēja pāri sliežu pārejai, lai varētu iekāpt gaidītajā vilcienā. Diemžēl es nevaru teikt, ka es nepieļāvu tādu pašu kļūdu. Redzot lielo cilvēku pūli, es izlēmu iet stāvēt kopā ar šo klasi. Tuvojoties vilcienam, es redzēju, ka tas nepienāks pie šī ceļa. Es laicīgi sāku iet uz pareizo ceļu un vēlāk man arī pievienojās iepriekšminētā klase. Vilcienā visi veiksmīgi iekāpām.',
    'text-name-brauciens' => 'Esmu atradis vietu vilcienā, aizveras durvis, un vilciens izbrauc no stacijas. Vilciens lēnām uzsāk kustību un drīz jau esam pabraukuši garām dzelzceļa pārbrauktuvei, kur paveras skats uz iepriekš minēto Rīgas ielu. Pirmā gaidīšana ir beigusies, tagad sākas stundu garais brauciens līdz Rīgai. Braucot ikdienā ar vilcienu, sāc atcerēties staciju secību, biļešu kontrolieru kustības maršrutu, kā arī gala stacijas atvadu sveicienu no “Pasažieru vilciena”. Tikai man liekas, ka šo sveicienu neesmu dzirdējis kādu laiku. Jo biežāk brauc, jo mazāk īpašas šīs detaļas lietas un tā ir daļa no tavas ikdienas rutīnas kā fona mūzika.',
    'text-description-brauciens-1' => 'Es neatceros pirmo reizi, kad braucu ar vilcienu. Agrā bērnībā līdz sāku iet skolā es dzīvoju Limbažos, caur kuru kādreiz gāja vilciens. Šo maršrutu slēdza jau deviņdesmitajos gados, un sliedes vēlāk noņēma. Tomēr man vēl no bērnības ir spilgti atmiņā palikuši stāsti par to, kā mana vecmamma kādreiz braukusi uz Rīgu ar vilcienu no Limbažiem. Līdz sāku dzīvot Siguldā, man nesanāca īpaši braukt ar vilcienu. Sākumskolas laikā dažreiz sanāca braukt uz Rīgu ar vilcienu. Pamatskolas beigās un, it īpaši vidusskolā, es daudz biežāk braucu uz Rīgu ar draugiem vai vienatnē. Pēc vidusskolas pabeigšanas un iestāšanās Latvijas Universitātē man bija nepieciešams izlemt, vai es sākšu dzīvot Rīgā vai braukāšu uz lekcijām no Siguldas. Es izlēmu nedomāt par pārvākšanos, līdz es iegūtu darbu kā programmētājs, un braukt katru rītu uz universitāti.',
    'text-description-brauciens-2' => 'Pirmais semestris iesākās ar mēnešbiļetes iegādāšanos. Pēc lekciju un vilciena saraksta salīdzināšanas, es sapratu, ka vilcienu pienākšanas/atiešanas laiki lieliski sakrīt ar lekciju sākuma/beigu laiku. Tāpēc, ka LU galvenā ēka atrodas netālu no Centrālās stacijas, es varēju mierīgi 10 minūšu laikā aiziet starp šīm ēkām. Braucot vilcienā, es varēju strādāt pie mājasdarbiem vai mēģināt kā citādi produktīvi aizpildīt laiku. Otrais semestris iesākās ļoti līdzīgi pirmajam, līdz sākās pandēmija. Kopš tā laika es neesmu vairs tik aktīvi braukājis no Siguldas uz Rīgu. Tikai 2022. gada pavasarī es sāku atkal regulāri braukt vairākas reizes nedēļā uz Rīgu, lai dotos uz lekcijām, uz darbu, lai satiktu draugus, kas tagad dzīvo Rīgā, u.tml. Šo gadu laikā es sapratu, ka šī stundu garā braukāšana vairāk ierobežo manas izvēles, kā pavadīt savu laiku. Lielākā daļa manu draugu un manas dzīves jau atrodas Rīgā. Es vien pats tur tikai viesojos.',
    'text-name-skatlogs' => 'Skatlogs. Skat, logs! Skatu logs. Paceļot acis no datora vai telefona vilciena brauciena laikā, paveras acis uz vienu no lielākajiem ieguvumiem braukšanai ar vilcienu - ceļošana atrauti no mašīnām vai autobusiem, kas ir lielākoties piesaistīti brauktuvei. Dzelžu ceļš, izlauzis savu ceļu caur dabu un pilsētām, piedāvā ieskatu gan zināmajā, gan nepazīstamajā no skatupunkta, kas nav pieejams autobraucējiem. Skats uz mežiem, skats uz pilsētām, skats uz mājām blakus dzelzceļam, skats uz noliktavām. Mūžam mainīgais skatlogs, kas mums rāda apkārtnes dabu un to, ko esam izvēlējušies izveidot kādreiz neskartās vides vietā. Tas ir skatlogs uz mūsu pagātni un mūsu attīstību. Tas ir skatlogs uz mums.',
    'text-description-skatlogs' => '',
    'text-name-galastacija' => 'Nākamā pietura – gala stacija RĪGA. Šie vārdi iezīmē vilciena brauciena beigu tuvošanos. Iepriekš starp ēkām iespiestās vilciena sliedes pēc Zemitāniem sāk pacelties uz augšu un nostāties blakus sliežu pāriem, kas ved uz citiem Latvijas galiem. Braucot paralēli Satekles ielai, var dzirdēt cilvēku rosību un gatavošanos izkāpšanai. Vissteidzīgākie jau dodas stāvēt pie durvīm. Vilciens turpina ceļu un sāk iebraukt stacijas teritorijā. Parādās peronu nojumes. Pārējie cilvēki, savas mantas savākuši, sāk virzīties uz kādu no vagona galiem un veido rindu izkāpšanai. Daži cilvēki vēl nesteidzas un turpina sēdēt līdz vilciens apstāsies. Ar jūtamu spēku var just, ka esam apstājušies. Durvis atveras, un cilvēku straume izplūst ārā un izklīst Centrālās stacijas biezoknī.',
    'text-description-galastacija' => '',
    'text-name-krustojums' => '',
    'text-description-krustojums' => '',
    'text-name-durvis' => 'Durvis ir kā sākums, tā beigas manam ceļam uz universitāti. Prātā man vispirms nāk abas smagās durvis, kas jāpūlas atvērt, lai tiktu universitātes ēkā. Bez tām vēl var padomāt par durvīm pārnestajā nozīmē. Pēc vidusskolas pabeigšanas es izvēlējos iet cauri durvīm ar nosaukumu “studijas Latvijas Universitātē”, aiz kurām atrodos vēl šobrīd. Ejamais ceļš ir miglains, bet tālumā var manīt nākamo izvēļu durvju kontūras. Man neviens nav iedevis karti, uz kuras teikts, kāds ceļš mani sagaidīs aiz durvīm. Vienīgais, ko varu ievērot, ir tas, ka durvju skaits pie katras tālākās izvēles tikai palielinās. Tuvojoties izvēlei, es mēģinu atcerēties, ka durvis aiz manis netiek aizslēgtas. Ja es nonāku neceļos, man ir iespēja apgriezties otrādi un aiziet izvēlēties citas durvis.',
    'text-description-durvis' => '',
];
