<?php

return [
    'button-lasit-vairak' => 'Read more',
    'button-apskatit-sadalas' => 'Show sections',

    'title-mans-cels-uz-universitati-1' => 'My journey',
    'title-mans-cels-uz-universitati-2' => 'to university',
    'title-marsruts' => 'Route',
    'title-par-nosaukumu' => 'About the name',
    'title-vairak-par-vietu' => 'More about the place',

    'text-title-pasteiga' => 'Dash',
    'text-name-pasteiga' => 'The short walk from my house to the train station is supposed to be a calm start to my day. The morning walk down Riga street that I got to know so well during my school years. Past the tree that was planted 10 years ago, but now is just as tall as the other trees around it. Remembering how when I was little, my grandmother would walk me home from school on this very same street. Amid this peaceful walk, I get a feeling I might miss my train. As I begin to rush, the morning walk becomes a dash.',
    'text-name-pasteiga-short' => 'The short walk from my house to the train station is supposed to be a calm start to my day. Amid this peaceful walk, I get a feeling I might miss my train. As I begin to rush, the morning walk becomes a dash.',
    'text-description-pasteiga-1' => 'Although I walk down several streets on my way to the station, the two main ones are Riga street and Stacijas street. Riga street connects the nearby Vidzemes highway to the city center, leading to a busy flow of cars throughout the day. To reach the train station, I must, unfortunately, cross Riga street. I say unfortunately, because the only crosswalk on Riga street is at the very end of it. Pedestrians at the other crossroads on the street must wait their turn to cross, so as not to get under the wheels of the passing cars. The nighttime, when all the drivers have gone to sleep, is the only time when pedestrians can take a breath when crossing. All the tension of the day is replaced with a feeling of peace, as the white streetlights illuminate the empty road.',
    'text-description-pasteiga-2' => 'Walking down Riga street, I can spot both the new and old houses. Several of them have been built or renovated since I started living in Sigulda. A few service buildings have been relocated to other spaces, for example, the old offices of “SEB” bank are now home to Sigulda Possibility House that joins under one roof different organizations that help people with special needs. A few years ago, bicycle lanes were painted on Riga street. Although cyclists use these lanes, their instalment hasn’t been very successful as they are not separated from the main part of the road by any physical features. This also highlights another shortcoming of Riga street – although a row of houses can be seen on both sides of the street, a sidewalk stretches along only one of these sides. As a result, some pedestrians use the bicycle lanes as a sidewalk.',
    'text-description-pasteiga-3' => 'I usually walk to the train station on foot, as it is located only 10 minutes away from my house. Still, I can make the distance by bike – this usually takes me approximately 5 minutes. I mostly choose the latter travel option during spring and summer time, as the weather is nice and sunny, and I can take a small bike detour on the way home once I arrive back from Riga. I also enjoy going on walks in the city. At the end of Riga street, I can make a turn on Stacijas street and walk parallel to the train tracks. Once I cross the tracks, I have reached the train station.',

    'text-title-gaidisana' => 'Waiting',
    'text-name-gaidisana' => 'I have arrived at my first destination and haven’t missed my train. If the train departs from Sigulda, I can board it and look for a seat. Otherwise, I have to wait for the train to arrive and take me and the other passengers towards the direction of Riga. Standing on the train platform, you can see more passengers arrive. Different people have arrived to head in the same direction, but not the same destination. I recognize some of them. Others, I see for the first and perhaps the only time. Although we don’t know each other, we are bonded by this moment of waiting. But once the train arrives, we disperse and move on with our lives, having just experienced this short and insignificant moment of togetherness among strangers.',
    'text-name-gaidisana-short' => 'I have arrived at my first destination and haven’t missed my train. I have to wait for the train to arrive and take me and the other passengers towards the direction of Riga.',
    'text-description-gaidisana-1' => 'I usually have some time to make my way around the station before the train arrives. I can use this time to see the Station square and its surrounding area. Since the renovation, the station combines both the central bus station as well as the train station with its tall “Laima” clock that Sigulda city acquired over ten years ago. The station is surrounded by two green zones on from both sides. One of these is a small park with the old water tower that now serves as an art gallery. The other is an overgrown, privately owned piece of land. For years, the proprietor has suggested to do construction work on this land, but it hasn’t happened yet. So, for now this green zone can be used to reach the train station after crossing the train tracks. Opposite the façade of the station lies Ausekļa street with its old buildings, cafes, shops and the very first bicycle street in Latvia – Pils street.',
    'text-description-gaidisana-2' => 'Sometimes you can start to worry whether you are waiting on the correct train platform. The train tickets that are purchased online via the official app don’t show which platform the train will depart from. Departure times can be seen inside the station building, however you will not find the platform of departure. In fact, a group of students, wanting to return to Riga from their field trip in Sigulda, recently made the mistake of waiting on the wrong platform. As the train arrived, they quickly crossed the tracks to board the train. Unfortunately, I made the same mistake. Seeing the crowd of students made me want to stand on the same platform as them. But even from afar I could see the train would stop at the other platform. So, I crossed the tracks, and soon after the students followed and we all boarded the train together.',

    'text-title-brauciens' => 'Journey',
    'text-name-brauciens' => 'I have found my seat on the train, the doors behind me close and the train leaves the station. As it slowly begins to leave the city, we cross the railroad crossing that runs across Riga street. The initial wait is over and the hour-long journey to Riga begins. Riding the train every day makes you memorize the order of the passing stations, the course the train conductor makes when checking tickets, as well as the goodbye message that is played as the train reaches Riga central station. Only it seems like I haven’t heard this message in a while. The more I make the journey, the more forgettable these small details become – they turn into my daily routine background music.',
    'text-name-brauciens-short' => 'I have found my seat on the train, the doors behind me close and the train leaves the station. The initial wait is over and the hour-long journey to Riga begins.',
    'text-description-brauciens-1' => 'I don’t remember the first time I rode the train. I spent my early childhood years living in Limbaži, through which the train used to pass. The route through Limbaži was closed off in the 90’s and the train tracks were later removed. Still, I remember the stories of how my grandmother would take the train from Limbaži to Riga. I didn’t really ride the train until I started living in Sigulda; then I would sometimes ride the train in primary school. Train rides by myself or with friends became a regular event for me in middle school and high school. After graduating from high school and getting accepted into the University of Latvia, I had to decide whether I was going to live in Riga or ride to Riga for my lectures every day. I decided to put off moving to Riga until I got a job as a programmer. In the meantime, I would ride the train every morning.',
    'text-description-brauciens-2' => 'The first semester of university began by me purchasing the monthly train ticket. After comparing train schedule and my weekly lecture schedule, I saw that train arrival/departure times perfectly coincide with the beginning and end of my lectures. Since my university faculty is located only 10 minutes away from Riga central station, I could easily make the walk. And I could spend the train ride by doing homework as some other tasks. The second semester started off similarly to the first, until the pandemic began. Since then, I haven’t been riding the train to Riga so often. My regular journey to Riga resumed only in the spring of 2022 so that I could attend lectures, go to work, meet my friends that live in Riga, etc. During these years I understood that the hour-long train ride limits options in how I choose to spend my time. Most of my friends and, in fact, my life is now in Riga. I am simply a guest there.',

    'text-title-skatlogs' => 'Storefront',
    'text-name-skatlogs' => 'If I raise my eyes from the phone or computer screen, I can observe one of the biggest benefits of riding the train – traveling apart from cars and buses that drive on the highway. The train tracks that have made their way through nature and cities offer a look into the known and unknown from a viewpoint not available to those driving in cars. The forests, cities, houses near the tracks, the warehouses. The ever-changing view of nature and everything we chose to create in the midst of it, once untouched by the human hand. It’s a window to our past and our progress. It’s a window to us.',
    'text-name-skatlogs-short' => 'The train tracks that have made their way through nature and cities offer a look into the known and unknown from a viewpoint not available to those driving in cars.',
    'text-description-skatlogs-1' => 'Once the train leaves Sigulda railway station, the view of the city is quickly replaced by forest landscapes. The train passes the nearby houses and then drives under Vidzeme highway which runs through Sigulda. The forests are shortly replaced by the view of Lorupe valley which reminds the passengers that Sigulda is located on higher terrain. If you look closely, you can catch a glimpse of the remnants of the recently closed train stations of Silciems and Baltezers. The small station houses are still named after the old station titles. The next biggest station after Sigulda is Inčukalns. At this point of the journey the view switches from thick forests to vast fields and timber warehouses. Driving once again under Vidzeme highway, the train arrives in Garkalne after which the tracks run parallel the highway. In certain spots, the pine tree forest parts and gives way to a view of the highway. As the train approaches Riga, the forests are replaced by warehouses, and you can make out Berģi through the trees. Once the train crosses the railway bridge, you get a feeling as if you’ve already arrived in Riga.',
    'text-description-skatlogs-2' => 'From the outside Jugla train station looks like all the previous stations. However, the main difference lies in the environment surrounding the station. The feeling of the tall buildings and movement suddenly weighing down on you – the difference in construction levels is obvious. Čiekurkalns station furthers this feeling by presenting a view of an old 19th century building adorned with the name of the station, a soviet-time building constructed next to the tracks and the tall newer buildings in the background – a familiar site that tells stories of our past and present. As the tracks curve and the train passes working and former industrial buildings, the presence of construction becomes evident. The second-to-last station – Zemitānu station – is neatly tucked away under bridges and reminds me of the former Limbaži train station. Since this is the second-to-last station before Riga central station, I turn away from the train window and start getting ready to get off at the final station.',

    'text-title-galastacija-1' => 'End',
    'text-title-galastacija-2' => 'station',
    'text-name-galastacija' => 'Next stop – RIGA central station. These words signify the end of the train ride. The train tracks, that were previously squeezed in between buildings, suddenly expand, and run along multiple other tracks that lead to other parts of Latvia. As the train drives parallel to Satekles street, the passengers shuffle around and get ready to step off the train. Some already make their way to the doors. The train continues its course into Riga central station and offers a view to the platforms. By now most of the passengers have collected their things and form a line leading up to the train door. The ones who aren’t in a hurry wait for the train to halt. The train comes to a stop with an apparent force. The doors slide open, and a stream of people gets off the train and scatters throughout the central station.',
    'text-name-galastacija-short' => 'Next stop – RIGA central station. These words signify the end of the train ride. The passengers shuffle around and get ready to step off the train. Some already make their way to the doors.',
    'text-description-galastacija-1' => 'The passengers from the Sigulda train aren’t the only ones getting off at Riga central station. Trains arrive even from the farther corners of Latvia such as Aizkraukle, Sloka, Krāslava etc. In the background you can hear the loud electric trains leave the station. You could say that it’s nothing worth mentioning. It might even beg the question of why the electric trains are just as loud or louder than the diesel trains. The sound captures my attention though, as I am used to the particular sound of the diesel trains at Sigulda train station. When the new electric trains arrive in Latvia and replace the old ones, I will have to get accustomed to their new sounds. Hopefully, the new trains will be quieter than the current electric trains.',
    'text-description-galastacija-2' => 'As I make my way down the station platform, I notice remnants of what the Central station used to be. The luminous lights that would greet the passengers at their arrival to the station, the old cafes and waiting spaces. Even though the clock tower was rebuilt approximately 20 years ago, it practically looks the same as the old tower that was built in the 60’s. The main station building is enclosed between a part of the station renovated in the early 2000’s and the newly built “Origo” shopping center. A blend of time periods that showcase the main purpose the station held over the decades.',

    'text-title-krustojums' => 'Intersection',
    'text-name-krustojums' => 'The title “Riga central station building” alludes to the unifying role of the station. This is one of the places in Riga where the paths of strangers’ merge and carry on in different directions. Every person that has arrived in Riga by train, rushes to the departing trains or visits the shopping center meets in one place. It’s similar to the “Waiting” section which described a place where people come together to travel in the same direction. Here, people have arrived from different places, but their further destinations differ. Still, everyone is united by the fleeting moment of togetherness that can be experienced when walking through the station building.',
    'text-name-krustojums-short' => 'The title “Riga central station building” alludes to the unifying role of the station. Here, people have arrived from different places, but their further destinations differ.',
    'text-description-krustojums' => 'Even though I have been praising the central station as a unifying force and train hub, I must admit that I am not fond of the current state of Riga central station. After the renovation of parts of the station in the early 2000’s, it is no longer just a train station. It’s a supermarket where the station is simply an additional feature. There’s no space for people to sit down and wait for their train. The layout of the station, the signs and overall mood of the station stirs unpleasant emotions. Even the station restrooms are notorious for the fact that you have to pay to get in, even though there aren’t any public restrooms in the nearby area. The train route and departure schedules have been replaced by small, ugly screens, while the interior walls are covered in commercial posters. The station is quite inaccessible and hasn’t been integrated with other means of public transportation. The tunnels that run under 13. janvāra street are a burden to pedestrians and sometimes lead to an unpleasant experience. 13. janvāra street, which is constantly packed with cars, delimits the station from the rest of the city. I have hope that some of these problems will be solved during the reconstruction of the station within the “Rail Baltica” project.',

    'text-title-durvis' => 'Door',
    'text-name-durvis' => 'A door marks both the beginning and the end for my journey to university. First, I think about the 2 heavy doors that I have to open in order to get in the university building. Besides that, you can think about doors figuratively. After finishing high school, I chose to go through the door named “studies at the University of Latvia” behind which I still am today. The road ahead is foggy, but in the distance I can see the outlines of the next doors awaiting my decision. Nobody has given me a map on which it says what kind of journey waits for me behind a door. The only thing I can notice is that the number of doors after each choice only gets larger. When approaching a choice, I try to remember that the door behind me does not get locked. If I choose the wrong door, I have the option to turn around and go choose another door to go through.',
    'text-name-durvis-short' => 'A door marks both the beginning and the end for my journey to university. First, I think about the 2 heavy doors that I have to open in order to get in the university building. Besides that, you can think about doors figuratively.',
    'text-description-durvis' => 'While following the crowd of people walking around Station square, I arrive at the pedestrian tunnels. Nowadays I can find the correct exit which leads to Rainis boulevard much more confidently. If I don’t pay attention then I can end up, for example, on the wrong side of the street or on the public transport stop that’s in the middle of Rainis boulevard. On sunny days it’s enjoyable to walk down Rainis boulevard because next to it is a park with a canal. When I arrive at the intersection of Rainis boulevard and Krišjānis Barons street I notice my destination – the main building of the University of Latvia. The light of the traffic light changes from red to green and I start walking across the street while trying not to trip over the tram tracks or the cobblestone. I have around ten minutes until the start of my lecture. I can see other students that are also going to their lectures. We climb up the stairs and after getting past the heavy doors we have reached the end.',
];
